# permissions for end users to edit generatedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: generatedsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: generated-secrets
    app.kubernetes.io/part-of: generated-secrets
    app.kubernetes.io/managed-by: kustomize
  name: generatedsecret-editor-role
rules:
- apiGroups:
  - secrets.k8s.k.io
  resources:
  - generatedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.k8s.k.io
  resources:
  - generatedsecrets/status
  verbs:
  - get
