apiVersion: secrets.k8s.k.io/v1
kind: GeneratedSecret
metadata:
  name: example-secret
spec:
  deleteSecretOnDelete: true
  keys:
    - name: base64
      type: Base64
      length: 10

    - name: base64url
      type: Base64URL
      length: 10

    - name: hex
      type: Hex
      length: 10

    - name: alphanumeric
      type: Alphanumeric
      length: 10

    - name: alphabetic
      type: Alphabetic
      length: 10

    - name: upper
      type: Upper
      length: 10

    - name: upperNumeric
      type: UpperNumeric
      length: 10

    - name: lower
      type: Lower
      length: 10

    - name: lower-numeric
      type: LowerNumeric
      length: 10

    - name: uuid
      type: UUID

    - name: dns-label
      type: DNSLabel
      length: 10

    - name: numeric
      type: Numeric
      length: 10

    - name: adam-string
      type: String
      length: 10
      string:
        charset: adam

    - name: ec256-key
      type: ECDSAKey
